### PR TITLE
refactor: remove hire section on oneclick settings on woocommerce panel

### PR DESCRIPTION
**Pull request by tribiec**
This PR removes the section to hire the service:

Before:
image

After:
Captura de pantalla 2024-01-18 a las 5 03 53 p m

### CODE REVIEW

**Review by isabellaahc — COMMENTED** [review]
missing evidence and pull request description

**Comment by Matiasnickolas** [comment]
In your evidence, you must display the result after deleting the hire section

**Review by mvarlic — APPROVED** [review]
LGTM!

**Review by Matiasnickolas — APPROVED** [review]
GJ 🤙

**Review by mastudillot — APPROVED** [review]
Lgtm

**Pull request merged**
